name: Bytecraft
author: Sabersamus
main: info.bytecraft.Bytecraft
description: The main plugin for Bytecraft
website: http://www.bytecraft.info
version: 1.3.1
commands:
    back:
        description: Go back to where you died... for a cost
        usage: /<command>
    ban:
        description: Ban a player from the server
        usage: /<command> <player>
    bless:
        description: Bless a block for a player
        usage: /<command> <player>
    brush:
        description: Create a brush
        usage: /brush <material> <radius>
    channel:
        description: Change your chat channel
        usage: /<command> <channel>
    chestlog:
        description: Change your chest log flag
        usage: /<command> <true|false>
        aliases: [clog]
    clear:
        description: Clear your inventory
        usage: /<command>
        aliases: [cl, clean] 
    cmob:
        description: Create a new mob
        usage: /<command> <mob> [amount] [name]
    cname:
        description: change yo name
        usage: /<command> <color> <name>
    creative:
        description: Change your gamemode to creative
        usage: /<command>
    fill:
        description: Fill some blocks
        usage: |
            /<command> <material>
            /<command> <oldMaterial> <newMaterial>
            /<command> copy
            /<command> paste [rotation]
            /<command> undo
    flag:
        description: See your flags
        usage: /<command>
    force:
        description: Force a player into a channel
        usage: /<command> <player> <channel> 
    gamemode:
        description: Change your gamemode
        usage: /<command> [creative|survival:1:2]
        aliases: [gm]
    give:
        description: Give another player an item
        usage: /<command> <player> <id|name> <amount> <data>
    god:
        description: Send a message as the default red god
        usage: /<command> <message>
    hardwarn:
        description: Hard warn a player, taking their build powers
        usage: /<command> <player> [amount] [minutes|hours|days|weeks|months]
    head:
        description: Spawn a player's head
        usage: /<command> <player>
    home:
        description: Manage your home
        usage: |
            /<command> go [name]
            /<command> save [name]
            /<command> delete [name]
    inv:
        description: View another players inventory
        usage: /<command> <player>
    item:
        description: Give yourself an item
        usage: /<command> <id|name> <amount> <data>
        aliases: [i]
    kick:
        description: Kick a player
        usage: /<command> <player> <message>
    kill:
        description: Kill yourself
        usage: /<command>
    lot:
        description: Manage a lot
        usage: |
            /<command> create <name>
            /<command> delete <name>
            /<command> addowner <name>
            /<command> delowner <name>
    makewarp:
        description: Make a new warp
        usage: /<command> <name>
    me:
        description: Send a message in third person
        usage: /<command> <message>
    message:
        description: Send a message to another player
        usage: /<command> <player> <message>
        aliases: [m, to, msg]
    mute:
        description: Mute a spammer
        usage: /<command> <player> x [minutes hours days weeks months years]
    newspawn:
        description: Set the spawn
        usage: /<command>
    nuke:
        description: Nuke mobs
        usage: /<command> [distance]
    pos:
        description: Get your global position
        usage: /<command>
        aliases: [coords]
    reply:
        description: Reply to your last message
        usage: /<command> <message>
        aliases: [r]
    ride:
        description: lolol
        usage: /<command> [target]
    rideme:
        description: lolol
        usage: /<command> [target]
    say:
        description: Send a message as god
        usage: /<command> <message>
    sell:
        description: Sell your items to the server
        usage: /<command>
    summon:
        description: Summon a player to your location
        usage: /<command> <player>
        aliases: [s, tphere]
    support:
        description: Send the staff an email for help
        usage: /<command> <message>
    smite:
        description: Smite a player!
        usage: /<command> <player>
    spawn:
        description: Teleport to spawn
        usage: /<command>
    survival:
        description: Change your gamemode to survival
        usage: /<command>
    testfill:
        description: Do a test fill that only shows until you log out
        usage: /<command> <material>
    time:
        description: Change your personal time
        usage: /<command> [day|night|normal]
    tool: 
        description: Use different tools
        usage: /<command> [workbench, wb]
    town:
        description: Manage your current zone
        usage: |
            /<command> adduser <player> <rank>
            /<command> deluser <player>
            /<command> info [perm]
            /<command> flag <hostiles|pvp|whitelist|build> <true|false>
            /<command> flag <entermsg|exitmsg> <message>
    tpblock:
        description: Manage your teleport block
        usage: /<command> <on|off|status>
    teleport:
        description: Teleport to a player
        usage: /<command> <player>
        aliases: [tp, tele]
    tppos:
        description: Teleport to co-ordinates
        usage: /<command> x y z
    user:
        description: Manage players permissions
        usage: /<command> make <setter|member> <player>
    vanish:
        description: Vanish
        usage: /<command> [silentjoin:sj|hiddenloc:hl
        aliases: [v, poof]
    wallet:
        description: Manage your wallet
        usage: |
            /<command> balance
            /<command> tell
            /<command> give <player> <amount>
    warn:
        description: Warn a player
        usage: /<command> <player> [amount] [minutes|hours|days|weeks|months]
    warp:
        description: Warp to a far away land
        usage: /<command> city
    who:
        description: See who's online
        usage: /<command> [player]
        aliases: [list]
    zone:
        description: Manage zones
        usage: |
            /<command> create <name>
            /<command> delete <name>
            /<command> adduser <name> <player> <permission>
            /<command> deluser <name> <player>
            /<command> flag <name> <pvp|whitelist|build|hostiles> <true|false>
            /<command> flag <entermsg|exitmsg> <name> <message>
            /<command> info <name> [perm]